// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"time"
)

type Post struct {
	ID         int32
	PostID     string
	CreatorDid string
	CreatedAt  time.Time
	Text       string
}

type PostTag struct {
	PostID    int32
	TagID     int32
	CreatedAt time.Time
}

type Tag struct {
	ID   int32
	Name string
}
