// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Post struct {
	ID        int32
	Title     string
	Content   string
	CreatedAt sql.NullTime
}

type PostTag struct {
	PostID int32
	TagID  int32
}

type Tag struct {
	ID   int32
	Name string
}
